description: Paperback 0.9 extensions maintained by CorruptBytes.
topics:
  - typescript
  - javascript
  - ios
  - mobile
  - manga
  - comics
  - manga-reader
  - comic-reader
  - authentication
  - paperback
  - paperback-extensions
  - vortex-scans
homepage: "https://michaelasper.github.io/paperback-corruptbytes/"
